### ISSUE TITLE
Add offset for overlapping points

### ISSUE THREAD

**Issue by ellyoana** [Scenwise/parking-widget-demo#25]
For large datasets (e.g., updated RWS data), a lot of accidents happen at the same hectopoint and thus they overlap on the map. Add some offset to make the distinction understandable.

**Comment by LibbyTang** [comment]
Offset is mainly for deviating the point from its original place. Setting the offset the same for all the points, the overlapping issue persists. Applying a uniform offset simply shifts all the points by the same amount, and makes they still overlap if they were overlapping before.

![image](https://github.com/user-attachments/assets/7d68c57f-60d4-4015-946a-37177994ffcc)

One solution is to set different offsets based on the road direction of the incident, but it seems that `circle-translate` (field for setting offset in a circle layer) does not support data expressions, which is 
```
        [
            "case",
            ["==", ["get", "zijde"], "R"], ["literal", [10, 0]],
            ["==", ["get", "zijde"], "L"], ["literal", [-10, 0]],
            ["literal", [0, 0]]
        ]

```
